blank_issues_enabled: false
contact_links:
  - name: QQ 交流群
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=6CgTYQPOlMKMxxshhdf3ZJwjt3qqK_87&authKey=Nq9BLEt4EpDQ5H%2Fr96PLFYymjbAifnwaICuBUDqpRCZfkfIC2uGW8CPtI%2FinUhWu&noverify=0&group_code=719540466
    about: 问题反馈，BUG交流
  - name: Telegram Group
    url: https://t.me/+yeQEhnuT9O41NDM1
    about: Problem feedback, BUG communication
